# Generated by Django 4.2.3 on 2023-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthexpert",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
