# Generated by Django 4.2.3 on 2023-07-06 17:57

from django.contrib.auth import get_user_model
from django.db import migrations

from base.models import HealthExpert, Doctor, HealthCenter


def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create(
        username='admin',
        password='admin',
        is_superuser=True,
        is_staff=True,
        is_active=True,
    )


def create_models(apps, schema_editor):
    User = get_user_model()
    HealthExpert.objects.create(
        user=User.objects.create(
            username='health_expert',
            password='health_expert',
        ),
        email="test@test.com",
        experience=10,
        skype_id="skype_id",
    )
    Doctor.objects.create(
        name="doctor",
        medical_id="medical_id",
        degree="degree",
    )
    HealthCenter.objects.create(
        name="health_center",
        address="address",
        work_fields="PS",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_healthexpert_last_login_organizationuser_last_login_and_more"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(create_models),
    ]
