# Generated by Django 4.2.3 on 2023-07-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_time', models.IntegerField()),
                ('approximate_price', models.FloatField()),
                ('prerequisites', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor')),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.healthcenter')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('paid', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], max_length=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.bill')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.service')),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packages.service')),
                ('datetime', models.DateTimeField()),
                ('therapeutic_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.therapeuticpackage')),
            ],
            bases=('packages.service',),
        ),
    ]
