# Generated by Django 4.2.3 on 2023-07-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="health_expert",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.healthexpert",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Canceled"), ("F", "Finished")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="reservation_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
