# Generated by Django 4.2.3 on 2023-07-06 18:15

from django.db import migrations

from packages.models import TherapeuticPackage
from base.models import HealthCenter, Doctor


def create_therapeutic_packages(apps, schema_editor):
    TherapeuticPackage.objects.create(
        name='Package 1',
        required_time=30,
        approximate_price=100,
        prerequisites='Prerequisites 1',
        health_center=HealthCenter.objects.get(name='health_center'),
        doctor=Doctor.objects.get(name='doctor'),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_reservation_health_expert_reservation_status_and_more"),
        ("base", "0003_auto_20230706_1757"),
    ]

    operations = [
        migrations.RunPython(create_therapeutic_packages),
    ]
