# Generated by Django 4.2.3 on 2023-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0003_auto_20230706_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerecord",
            name="status",
            field=models.CharField(
                choices=[("P", "Paid"), ("R", "Prepaid"), ("U", "Unpaid")], max_length=1
            ),
        ),
    ]
