# Generated by Django 4.2.3 on 2023-07-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230706_1757'),
        ('packages', '0004_alter_servicerecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticPackageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('therapeutic_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.therapeuticpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
    ]
